export default [
	"http://www.todo-chistes.com/chistes-al-azar?page=1" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=2" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=3" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=4" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=5" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=6" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=7" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=8" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=9" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=10" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=12" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=13" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=15" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=16" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=17" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=18" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=19" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=20" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=21" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=22" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=23" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=24" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=25" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=26" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=27" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=28" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=29" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=30" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=31" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=32" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=33" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=34" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=35" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=36" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=37" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=38" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=39" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=40" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=41" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=42" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=43" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=44" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=45" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=46" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=47" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=48" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=49" ,
	"http://www.todo-chistes.com/chistes-al-azar?page=50" ,
	"https://chistes.yavendras.com/vuestros.php",
	"https://chistes.yavendras.com/adivinanzas.php",
	"https://chistes.yavendras.com/amigos.php",
	"https://chistes.yavendras.com/animales.php",
	"https://chistes.yavendras.com/ano-nuevo.php",
	"https://chistes.yavendras.com/borrachos.php",
	"https://chistes.yavendras.com/buenos.php",
	"https://chistes.yavendras.com/chinos.php",
	"https://chistes.yavendras.com/colombianos.php",
	"https://chistes.yavendras.com/colorados.php",
	"https://chistes.yavendras.com/cristianos.php",
	"https://chistes.yavendras.com/crueles.php",
	"https://chistes.yavendras.com/escuela.php",
	"https://chistes.yavendras.com/feministas.php",
	"https://chistes.yavendras.com/feos.php",
	"https://chistes.yavendras.com/frikis.php",
	"https://chistes.yavendras.com/futbol.php",
	"https://chistes.yavendras.com/gallegos.php",
	"https://chistes.yavendras.com/gays.php",
	"https://chistes.yavendras.com/gordos.php",
	"https://chistes.yavendras.com/graciosos.php",
	"https://chistes.yavendras.com/groseros.php",
	"https://chistes.yavendras.com/negro.php",
	"https://chistes.yavendras.com/infantiles.php",
	"https://chistes.yavendras.com/jaimito.php",
	"https://chistes.yavendras.com/machistas.php",
	"https://chistes.yavendras.com/maestros.php",
	"https://chistes.yavendras.com/malos.php",
	"https://chistes.yavendras.com/mejores.php",
	"https://chistes.yavendras.com/mexicanos.php",
	"https://chistes.yavendras.com/navidad.php",
	"https://chistes.yavendras.com/para-ninos.php",
	"https://chistes.yavendras.com/no-es-lo-mismo.php",
	"https://chistes.yavendras.com/pepito.php",
	"https://chistes.yavendras.com/que-le-dice.php",
	"https://chistes.yavendras.com/se-abre-el-telon.php",
	"https://chistes.yavendras.com/suegras.php",
	"https://chistes.yavendras.com/verdes.php",	
	"https://www.1000chistes.com/chistes-de-abogados" ,
	"https://www.1000chistes.com/chistes-de-amigos" ,
	"https://www.1000chistes.com/chistes-de-ancianos" ,
	"https://www.1000chistes.com/chistes-de-animales" ,
	"https://www.1000chistes.com/chistes-de-azafatas" ,
	"https://www.1000chistes.com/chistes-de-borrachos" ,
	"https://www.1000chistes.com/chistes-buenos" ,
	"https://www.1000chistes.com/chistes-de-camareros" ,
	"https://www.1000chistes.com/chistes-de-catalanes" ,
	"https://www.1000chistes.com/chistes-cortos" ,
	"https://www.1000chistes.com/chistes-de-dinero" ,
	"https://www.1000chistes.com/chistes-de-drogas" ,
	"https://www.1000chistes.com/chistes-de-farmaceuticos" ,
	"https://www.1000chistes.com/chistes-de-frikis" ,
	"https://www.1000chistes.com/chistes-de-funcionarios" ,
	"https://www.1000chistes.com/chistes-de-gays" ,
	"https://www.1000chistes.com/chistes-de-infidelidad" ,
	"https://www.1000chistes.com/chistes-de-informatica" ,
	"https://www.1000chistes.com/chistes-de-ingenieros" ,
	"https://www.1000chistes.com/chistes-internacionales" ,
	"https://www.1000chistes.com/chistes-de-jaimito" ,
	"https://www.1000chistes.com/chistes-de-ladrones" ,
	"https://www.1000chistes.com/chistes-de-largos" ,
	"https://www.1000chistes.com/chistes-de-lepe" ,
	"https://www.1000chistes.com/chistes-malos" ,
	"https://www.1000chistes.com/chistes-de-matrimonios" ,
	"https://www.1000chistes.com/chistes-de-militares" ,
	"https://www.1000chistes.com/chistes-de-mdicos" ,
	"https://www.1000chistes.com/chistes-de-medicos" ,
	"https://www.1000chistes.com/chistes-de-navidad" ,
	"https://www.1000chistes.com/chistes-de-nios" ,
	"https://www.1000chistes.com/chistes-de-ninos" ,
	"https://www.1000chistes.com/chistes-de-parejas" ,
	"https://www.1000chistes.com/chistes-de-pastores" ,
	"https://www.1000chistes.com/chistes-de-perros" ,
	"https://www.1000chistes.com/chistes-de-politicos" ,
	"https://www.1000chistes.com/chistes-de-profesiones" ,
	"https://www.1000chistes.com/chistes-de-profesores" ,
	"https://www.1000chistes.com/chistes-de-religin" ,
	"https://www.1000chistes.com/chistes-de-religion" ,
	"https://www.1000chistes.com/chistes-de-restaurantes" ,
	"https://www.1000chistes.com/chistes-de-suegras" ,
	"https://www.1000chistes.com/chistes-de-telon" ,
	"https://www.1000chistes.com/chistes-de-tontos" ,
	"https://www.1000chistes.com/chistes-varios" ,
	"https://www.1000chistes.com/chistes-de-vascos" ,
	"https://www.1000chistes.com/chistes-de-vecinos" ,
	"https://www.1000chistes.com/chistes-verdes" ,
	"https://www.1000chistes.com/chistes-de-zapatos" ,
	
]