name: 16-minute-cron
on:
  schedule:
    - cron: '*/16 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://cubablog.net/cron' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
